### PR TITLE
Add user address resource and geocoding

### PR DESCRIPTION
**Pull request by Volqano**
- Add address resource
- Add geocode_address function
- Update documentation
- Update database to store longitude and latitude
- Note: PostGIS not implemented yet
❗️IMPORTANT❗️
You need to rebuild your database locally due to changes in the database setup

### CODE REVIEW

**Comment by JanKaczmarski** [comment]
So regarding testing and precisely the lack of it. I think we should wait for tests before merging. It's unwise to do it other way because we can possibly push buggy code and later on it might be hard to find the issue. So please wait a bit longer for tests to be fixed. I am close to fixing this issue with testing so the issue should be finished this weekend

**Comment by JanKaczmarski** [comment]
Please attach some tutorial for database rebuild, in comment under this PR

**Comment by JanKaczmarski** [comment]
Also, when creating PR attach 2 people for review this way you will let them know that their assistance is needed

**Comment by Volqano** [comment]
to rebuild database:
```
make stop
docker compose down --remove-orphans
sudo rm -rf /var/tmp/heaven_in_mouth_db_data/*
make init
```

**Comment by JanKaczmarski** [comment]
> So regarding testing and precisely the lack of it. I think we should wait for tests before merging. It's unwise to do it other way because we can possibly push buggy code and later on it might be hard to find the issue. So please wait a bit longer for tests to be fixed. I am close to fixing this issue with testing so the issue should be finished this weekend

I already fixed the issue with `make test` in this #87 PR. So please proceed with adding tests

**Review by maciusmajor — APPROVED** [review]

**Review by JanKaczmarski — APPROVED** [review]

**Pull request merged**
